trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureContainerApps@0
  inputs:
    appSourcePath: 'DevCon2023'
    azureSubscription: 'Azure DevTest subscription 1(81fbcae9-7964-4d10-8c0f-979d8e3a0d7a)'
    acrName: 'devcon2023'
    dockerfilePath: 'Dockerfile'
    imageToBuild: 'DevCon2023.azurecr.io/devcon2023:latest'
    containerAppName: 'devcon2023'
    resourceGroup: 'DevCon2023'
