trigger:
- main

pool:
  vmImage: 'linux-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureWebApp@1
  displayName: 'Publish'
  inputs:
    azureSubscription: 'Pay-As-You-Go(1)(f6a87188-5eec-4f5e-b859-e826e0106dbd)'
    appType: 'webApp'
    appName: 'silkdevcon'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deploymentMethod: 'auto'