trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'DevCon/DevCon/DevCon.csproj'
    arguments: '-c Release -o $(Build.ArtifactStagingDirectory)/devcon/'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: 'Deploy'
  inputs:
    azureSubscription: 'Pay-As-You-Go(1)(f6a87188-5eec-4f5e-b859-e826e0106dbd)'
    appType: 'webApp'
    appName: 'srpdevcon'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deploymentMethod: 'auto'